version: '2'
services:
  db:
    image: postgres
  web:
    image: rails_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "../src:/home/app/rails"
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
    command: bash -lc "./wait_forever"
  hello:
    image: hello-world
