development: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: sandbox_production
  username: sandbox
  password: <%= ENV['SANDBOX_DATABASE_PASSWORD'] %>
